project:
  type: website
  output-dir: docs
  
website:
  title: "Statistical Analysis in Medical Research Using R"
  reader-mode: true
  sidebar:
    style: floating
    search: true
    contents: 
      - section: "Home"
        contents:
          - index.qmd
      - section: "Introduction"
        contents:
          - Chapter01_Introduction.qmd
          - Chapter02_BasicProgramming.qmd
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
editor: visual