project:
  title: "StatisticalInMedicalResearch"
  type: website
  output-dir: docs
  
website:
  title: "StatisticalInMedicalResearch"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: floating
    search: true
    contents: 
      - section: "Home"
        contents:
          - index.qmd
      - section: "Introduction"
        contents:
          - Chapter01_Introduction.qmd
          - Chapter02_BasicProgramming.qmd
editor: visual